# templates/sat-token-secret.yaml
{{- if eq .Values.appAuthType "sat" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sat-token
type: Opaque
data:
  token: {{ .Values.satToken | default "" | quote }}
{{- end }}