# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  httpusername: {{ .Values.secret.httpUsername | b64enc }}
  httppassword: {{ .Values.secret.httpPassword | b64enc }}
  sqlpassword: {{ .Values.secret.sqlPassword | b64enc }}