apiVersion: v1
kind: Secret
metadata:
  name: console-app-secret
type: Opaque
data:
  username: aHA= # Base64 encoded username
  password: YWxvaG9tb3Jh  # Base64 encoded password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-app-deployment
  template:
    metadata:
      labels:
        app: console-app-deployment
    spec:
      containers:
      - name: console-app-deployment
        image: dockeroliva/context-app-for-dss:test3
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: console-app-config
        env:
        - name: HTTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: console-app-secret
              key: username
        - name: HTTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: console-app-secret
              key: password
        - name: CA_FILE_PATH
          value: "/app/certs/cafile.crt"
        - name: SAT_TOKEN_PATH
          value: "/app/secrets/sat_token"
        volumeMounts:
        - name: ca-cert-file
          mountPath: /app/certs
          readOnly: true
        - name: sat-token
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: ca-cert-file
        secret:
          secretName: test-ca
          items:
          - key: tls.crt
            path: cafile.crt
      - name: sat-token
        secret:
          secretName: sat-token-secret
          items:
          - key: token
            path: sat_token
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-app-config
data:
  HTTP_BASE_URL: "http://my-backend-api-s.default.svc.cluster.local:80" # The URL of the backend API. Replace with your own value.
  HTTP_PATH: "contexts/quality"
  REQUEST_INTERVAL_SECONDS: "10"
  AUTH_TYPE: "httpbasic"
  ENDPOINT_TYPE: "http"
  DSS_KEY: "quality"
  MQTT_HOST: "10.43.210.148" # The ip of the BROKER API. Replace with your own value.
  MQTT_CLIENT_ID: "console-app" # The client ID of the MQTT client. Replace with your own value.
  USE_TLS: "true"