apiVersion: v1
kind: Secret
metadata:
  name: console-app-secret
type: Opaque
data:
  httpusername: aHA= # Base64 encoded username
  httppassword: YWxvaG9tb3Jh  # Base64 encoded password
  sqlpassword: TXlFeHRyZW1lbHlTdHJvbmdwYXNzd29yZEAxMjM=  # MyExtremelyStrongpassword@123