apiVersion: v1
kind: Secret
metadata:
  name: console-app-secret
type: Opaque
data:
  username: aHA=  # Base64 encoded username
  password: YWxvaG9tb3Jh  # Base64 encoded password
  sqlusernameadmin: c2E=
  sqlpasswordadmin: WW91clN0cm9uZ1Bhc3N3b3JkMTIzIQ==  # Base64 encoded "YourStrongPassword123!"
  sqlusername: c2FtcGxldXNlcg==  # This is the base64 encoded version of 'sampleuser'
  sqlpassword: TmV3Q29tcGxleFBAc3N3MHJkMTIzJA==  # This is the base64 encoded version of 'NewComplexP@ssw0rd123$'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console-app-deployment
  template:
    metadata:
      labels:
        app: console-app-deployment
    spec:
      containers:
      - name: console-app-deployment
        image: dockeroliva/context-app-for-dss:v12
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: console-app-config
        env:
        - name: HTTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: console-app-secret
              key: username
        - name: HTTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: console-app-secret
              key: password
        - name: SQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: console-app-secret
              key: sqlusername
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: console-app-secret
              key: sqlpassword
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: console-app-config
data:
  HTTP_BASE_URL: "http://my-backend-api-s.default.svc.cluster.local:80" # The URL of the backend API. Replace with your own value.
  HTTP_PATH: "contexts/quality"
  REQUEST_INTERVAL_SECONDS: "10"
  AUTH_TYPE: "sqlbasic" # sqlbasic
  ENDPOINT_TYPE: "sql" # sql
  DSS_KEY: "quality"
  MQTT_HOST: "10.43.5.30" # The ip of the BROKER API. Replace with your own value.
  MQTT_CLIENT_ID: "console-app" # The client ID of the MQTT client. Replace with your own value.

  SQL_SERVER_NAME: "sqlserver-service"
  SQL_DB_NAME: "MySampleDB"
  SQL_TABLE_NAME: "CountryMeasurements"