apiVersion: v1
kind: Secret
metadata:
  name: console-app-credentials
type: Opaque
data:
  username: aHA=  # Base64 encoded username
  password: YWxvaG9tb3Jh  # Base64 encoded password
  sqlpassword: WW91clN0cm9uZ1Bhc3N3b3JkMTIzIQ==  # Base64 encoded "YourStrongPassword123!"
  sqlusername: c2E= 