apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
type: Opaque
data:
  # Replace these with base64 encoded values of your username and password
  SA_PASSWORD: WW91clN0cm9uZ1Bhc3N3b3JkMTIzIQ==  # Base64 encoded "YourStrongPassword123!"
  sqlpassword: WW91clN0cm9uZ1Bhc3N3b3JkMTIzIQ==  # Base64 encoded "YourStrongPassword123!"
  sqlusername: c2E=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: SA_PASSWORD
            - name: SQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: sqlusername
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-secret
                  key: sqlpassword
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-data

---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
